### ISSUE TITLE
pytest test runner fails when running under `plz cover`

### ISSUE THREAD

**Issue by chrisnovakovic** [please-build/python-rules#92]
With `python.test_runner = "pytest"` and `python.testrunner_deps = "///python//third_party/python:pytest_bootstrap"`, `plz cover` on a `python_test` fails with the following error:

```
bash-4.4$ $TEST
Traceback (most recent call last):
  File "[...]/python/python3.10/python3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "[...]/python/python3.10/python3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/plz_sandbox/[...]/__main__.py", line 488, in <module>
  File "/tmp/plz_sandbox/[...]/__main__.py", line 472, in run
  File "/tmp/plz_sandbox/[...]/__main__.py", line 409, in main
  File "/tmp/plz_sandbox/[...]/__main__.py", line 382, in initialise_coverage
ModuleNotFoundError: No module named 'coverage'
```

This appears to be because coverage isn't part of the built-in pytest test runner, nor are several other third-party packages required by `plz cover`.

**Comment by chrisnovakovic** [comment]
Fixed in #96.
